// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgdoogejjvoovxbtnnxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnZG9vZ2VqanZvb3Z4YnRubnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODg5MTUsImV4cCI6MjA2NDg2NDkxNX0.M-ccXkBl7WdEdMK1xbchr3MpdWzmi33BhK8hJ59aHPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);