import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// This file is automatically generated. Do not edit it directly.

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://fgdoogejjvoovxbtnnxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnZG9vZ2VqanZvb3Z4YnRubnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODg5MTUsImV4cCI6MjA2NDg2NDkxNX0.M-ccXkBl7WdEdMK1xbchr3MpdWzmi33BhK8hJ59aHPE";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase configuration. Please check your environment variables.');
}

console.debug('Supabase Config:', { 
  url: SUPABASE_URL, 
  keyPrefix: SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...',
  fromEnv: !!import.meta.env.VITE_SUPABASE_URL 
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});